Restore PageRevision reference in initial migration
We cannot reference a model that does not exist yet in the migration
history of existing databases. Migrating would fail with the following
error:

> ValueError: The field wagtail_ab_testing.AbTest.variant_revision was declared with a lazy reference to 'wagtailcore.revision', but app 'wagtailcore' doesn't provide model 'revision'.